name: ZIProxy Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Configure environment for cross-compilation
        run: |
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV
          echo "EXTENSION=${{ matrix.goos == 'windows' && '.exe' || '' }}" >> $GITHUB_ENV

      - name: Build
        run: |
          mkdir -p dist/${{ matrix.goos }}_${{ matrix.goarch }}
          GOOS=${{ env.GOOS }} GOARCH=${{ env.GOARCH }} go build -o dist/${{ matrix.goos }}_${{ matrix.goarch }}/ziproxy${{ env.EXTENSION }} ./

      - name: Add config.json and static files
        run: |
          cp config.json dist/${{ matrix.goos }}_${{ matrix.goarch }}/
          cp -r static dist/${{ matrix.goos }}_${{ matrix.goarch }}/

      - name: Archive build artifacts
        run: |
          tar -czf dist/ziproxy_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz -C dist/${{ matrix.goos }}_${{ matrix.goarch }} .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ziproxy_${{ matrix.goos }}_${{ matrix.goarch }}
          path: dist/${{ matrix.goos }}_${{ matrix.goarch }}